name: nginx-ci-prod
on:
  repository_dispatch:
    types: [fe-build-prod]
  workflow_dispatch:

env:
  IMAGE_NAME: meogle-nginx

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_HASH_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_HASH_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./nginx/prod
          file: ./nginx/prod/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_HASH_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ secrets.DOCKER_HUB_HASH_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_HASH_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_HASH_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache,mode=max